version: '3.9'
services:
  postgres:
    image: postgres:15.1
    restart: always
    user: root
    environment:
      POSTGRES_DATABASE: 'crosstime'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'crosstime'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'crosstime'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgresData:/var/lib/postgresql/data
volumes:
  postgresData: